// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwqGJZFlUEi6XKXDXGH6FcldwZSvT9zRo',
    appId: '1:890128361072:web:ad79817e54db54f0e6b6b5',
    messagingSenderId: '890128361072',
    projectId: 'confo0',
    authDomain: 'confo0.firebaseapp.com',
    storageBucket: 'confo0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-9CP9fYFsCu3p2OE0EJ7s8586ABq3_k',
    appId: '1:890128361072:android:b432de06f06667a5e6b6b5',
    messagingSenderId: '890128361072',
    projectId: 'confo0',
    storageBucket: 'confo0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqem6tVZQCPDtw0YtesmIkf0fX1FwR4I',
    appId: '1:890128361072:ios:81c51e89c04c1915e6b6b5',
    messagingSenderId: '890128361072',
    projectId: 'confo0',
    storageBucket: 'confo0.firebasestorage.app',
    iosBundleId: 'com.example.confo',
  );
}
